name: fields_generator
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  analyzer: '>=5.2.0 <7.0.0'
  build: ^2.0.0
  source_gen: any

dev_dependencies:
  dart_flutter_team_lints: ^2.0.0

dependency_overrides:
  source_gen: ^1.5.0
